[[edge_functions]]
  path = "/en/eco-tour/*"
  function = "tour-seo"

[[edge_functions]]
  path = "/ru/eco-tour/*"
  function = "tour-seo"

[[edge_functions]]
  path = "/hy/eco-tour/*"
  function = "tour-seo"

[[edge_functions]]
  path = "/en/group-tour/*"
  function = "tour-seo"

[[edge_functions]]
  path = "/ru/group-tour/*"
  function = "tour-seo"

[[edge_functions]]
  path = "/hy/group-tour/*"
  function = "tour-seo"

[[edge_functions]]
  path = "/en/private-tours/*"
  function = "tour-seo"

[[edge_functions]]
  path = "/ru/private-tours/*"
  function = "tour-seo"

[[edge_functions]]
  path = "/hy/private-tours/*"
  function = "tour-seo"

[[redirects]]
  from = "https://parmanitour.netlify.app/*"
  to = "https://www.parmanitour.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200
  force = true
